// Frameworks/Vue/00_start/src/pages/MemberListContainer.vue
<template>
  <div>
    <header-component/>
    <look-up-component
      :loading="loading"
      :organization-name="organizationName"
      @org-name-change="setOrganizationName"
      @page-value-change="setPageLimit"
      @load-members="loadAllMembers"
      @reset-data="resetData"
    />
    <list-component
      :api-response="apiResponse"
      :offset="currentOffset"
      :page-limit="pageLimit"
      @handle-paging="handlePaging"
    />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { HeaderComponent, LookUpComponent, ListComponent } from "./components";
import { ApiResponse, createDefaultApiResponse } from "../model/member";
import { memberAPI } from "../api/memberAPI";

export default Vue.extend({
  name: "MemberListContainer",
  components: { HeaderComponent, LookUpComponent, ListComponent },
  data: () => ({
    loading: false,
    organizationName: "lemoncode",
    pageLimit: 5,
    currentOffset: 0,
    apiResponse: createDefaultApiResponse() as ApiResponse
  }),
  methods: {
    loadMembers: function() {
      if (this.organizationName.length > 0) {
        this.loading = true;

        memberAPI
          .getAllMembers(
            this.organizationName,
            this.pageLimit,
            this.currentOffset
          )
          .then(apiResponse => {
            this.apiResponse = apiResponse;
          });
      }
    },
    loadAllMembers: function() {
      this.currentOffset = 0;
      this.loadMembers();
    },
    setOrganizationName: function(value: string) {
      this.organizationName = value;
      this.currentOffset = 0;
      this.apiResponse = createDefaultApiResponse();
    },
    setPageLimit: function(value: number) {
      this.pageLimit = value;
    },
    resetData: function() {
      this.organizationName = "";
      this.currentOffset = 0;
      this.apiResponse = createDefaultApiResponse();
    },
    handlePaging: function(page: number) {
      this.currentOffset = this.pageLimit * (page - 1);
      this.loadMembers();
    }
  },
  watch: {
    apiResponse() {
      this.loading = false;
    }
  }
});
</script>

// Frameworks/React/00_start/src/pages/memberListContainer.tsx
import * as React from "react";
import { ApiResponse, createDefaultApiResponse } from "../model/member";
import { memberAPI } from "/../api/memberAPI";
import { MemberLookupComponent } from "./components/memberLookup";
import { MemberListComponent } from "./components/memberList";

interface Props {}

interface State {
  apiResponse: ApiResponse;
}

export class MembersListContainer extends React.Component<Props, State> {
  public pageLimit = 5;
  public currentOffset = 0;
  public currentOrgName = "";

  constructor(props: Props) {
    super(props);
    this.state = { apiResponse: createDefaultApiResponse() };
  }

  loadOrganization = (orgName: string) => {
    this.currentOrgName = orgName;
    this.currentOffset = 0;
    this.loadMembers();
  };

  resetOrganization = () => {
    this.currentOrgName = "";
    this.currentOffset = 0;
    this.setState({ apiResponse: createDefaultApiResponse() });
  };

  setPageLimit = (pageLimit: number) => {
    this.pageLimit = pageLimit;
  };

  handlePaging = (offset: number) => {
    this.currentOffset = offset;
    this.loadMembers();
  };

  loadMembers = () => {
    if (this.currentOrgName.length > 0) {
      memberAPI
        .getAllMembers(this.currentOrgName, this.pageLimit, this.currentOffset)
        .then(apiResponse => this.setState({ apiResponse: apiResponse }));
    }
  };

  public render() {
    return (
      <>
        <MemberLookupComponent
          loadOrganization={this.loadOrganization}
          resetOrganization={this.resetOrganization}
          setPageLimit={this.setPageLimit}
        />
        <MemberListComponent
          pageLimit={this.pageLimit}
          currentOffset={this.currentOffset}
          apiResponse={this.state.apiResponse}
          handlePaging={this.handlePaging}
        />
      </>
    );
  }
}
